[#clusterInstance-api]
= ClusterInstance API

[[_rhacm-docs_apis_clusterinstance_jsonoverview]]
== Overview
This documentation is for the ClusterInstance resource for {acm}. The ClusterInstance resource has four possible requests: create, query, delete and update.

=== Version information
[%hardbreaks]
__Version__ : 2.12.0

=== URI scheme
[%hardbreaks]
__BasePath__ : /kubernetes/apis
__Schemes__ : HTTPS

=== Tags

* siteconfig.open-cluster-management.io : Create and manage clusters

[[_rhacm-docs_apis_clusterinstance_jsonpaths]]
== Paths

[[_rhacm-docs_apis_clusterinstance_jsonqueryclusters]]
=== Query all clusters
....
GET /siteconfig.open-cluster-management.io/v1alpha1/managedclusters
....

==== Description
Query your clusters for more details.

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|===

==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===

==== Consumes

* `clusterinstance/yaml`

==== Tags

* siteconfig.open-cluster-management.io

[[_rhacm-docs_apis_clusterinstance_jsoncreatecluster]]
=== Create a cluster
....
POST /siteconfig.open-cluster-management.io/v1alpha1/managedclusters
....

==== Description
Create a cluster

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Body*|*body* +
__required__|Parameters describing the cluster to be created.|<<_rhacm-docs_apis_clusterinstance_jsoncluster,Cluster>>
|===

==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===

==== Consumes

* `clusterinstance/yaml`

==== Tags

* siteconfig.open-cluster-management.io

==== Example HTTP request

===== Request body
[source,json]
----
{
  "apiVersion" : "siteconfig.open-cluster-management.io/v1alpha1",
  "kind" : "ManagedCluster",
  "metadata" : {
    "labels" : {
      "vendor" : "OpenShift"
    },
    "name" : "cluster1"
  },
  "spec": {
    "hubAcceptsClient": true,
    "managedClusterClientConfigs": [
      {
        "caBundle": "test",
        "url": "https://test.com"
      }
    ]
  },
  "status" : { }
}
----

[[_rhacm-docs_apis_clusterinstance_jsonquerycluster]]
=== Query a single cluster
....
GET /siteconfig.open-cluster-management.io/v1alpha1/managedclusters/{cluster_name}
....

==== Description
Query a single cluster for more details.

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*cluster_name* +
__required__|Name of the cluster that you want to query.|string
|===

==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===

==== Tags

* siteconfig.open-cluster-management.io

[[_rhacm-docs_apis_clusterinstance_jsondeletecluster]]
=== Delete a cluster
....
DELETE /siteconfig.open-cluster-management.io/v1alpha1/managedclusters/{cluster_name}
....

....
DELETE /hive.openshift.io/v1/{cluster_name}/clusterdeployments/{cluster_name}
....

==== Description
Delete a single cluster

==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|*Header*|*COOKIE* +
__required__|Authorization: Bearer {ACCESS_TOKEN} ; ACCESS_TOKEN is the user access token.|string
|*Path*|*cluster_name* +
__required__|Name of the cluster that you want to delete.|string
|===

==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|*200*|Success|No Content
|*403*|Access forbidden|No Content
|*404*|Resource not found|No Content
|*500*|Internal service error|No Content
|*503*|Service unavailable|No Content
|===

==== Tags

* siteconfig.open-cluster-management.io

[[_rhacm-docs_apis_clusterinstance_jsondefinitions]]
== Definitions

[[_rhacm-docs_apis_clusterinstance_jsoncluster]]
=== Cluster

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*apiVersion* +
__required__|The versioned schema of the `ManagedCluster`.|string
|*kind* +
__required__|String value that represents the REST resource.|string
|*metadata* +
__required__|The metadata of the `ManagedCluster`.|object
|*spec* +
__required__|The specification of the `ClusterInstance`. |<<_rhacm-docs_apis_clusterinstance_jsoncluster_spec,spec>>
|*status* +
__required__|The specification of the `ManagedCluster`. |<<_rhacm-docs_apis_clusterinstance_jsoncluster_status,status>>object
|===

// Everything below this line can be peer-reviewed. Everything above it needs SME review.

[[_rhacm-docs_apis_clusterinstance_jsoncluster_spec]]
*spec*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*additionalNTPSources* +
__optional__|Specify the NTP sources that needs to be added to all cluster hosts. They are added to any NTP sources that were configured through other means.|array
|*baseDomain* +
__required__|Specify the base domain used for the deployed cluster.|string
|*caBundleRef* +
__optional__|Reference the `ConfigMap` object that contains the new bundle of trusted certificates for the host.
The `tls-ca-bundle.pem` entry in the `ConfigMap` object is written to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`.|string
|*clusterName* +
__required__|Specify the name of the cluster.|string
|*clusterNetwork* +
__optional__|CSpecify the list of the IP address pools for pods.|array
|*clusterType* +
__optional__|CSpecify the cluster type. 
The following values are supported:

`SNO`:: {sno}
`HighlyAvailable`:: Multi-node OpenShift|string
|*cpuPartitioningMode* +
__optional__|Determine clusters to be set up for CPU workload partitioning at install time.
Configure workload partitioning by setting the value for `cpuPartitioningMode` to `AllNodes`.
To complete the configuration, specify the `isolated` and `reserved` CPUs in the `PerformanceProfile` CR.
The default value is `None`.|string
|*diskEncryption* +
__optional__|CEnable or disable disk encryption for the cluster.|object
|*extraAnnotations* +
__optional__|CSpecify additional cluster-level annotations to be applied to the rendered templates.|object
|*extraLabels* +
__optional__|Specify additional cluster-level labels that applies to the rendered templates.|object
|*extraManifestsRefs* +
__optional__|CSpecify the list of the `ConfigMap` object references that contain additional manifests to be applied to the cluster.|array
|*holdInstallation* +
__optional__|CSet to `true` to prevent installation when using the Assisted Installer.
You can complete the inspection and validation steps, but after the `RequirementsMet` condition becomes `true`, the installation does not begin until the `holdInstallation` field is set to `false`.|bool
|*ignitionConfigOverride* +
__optional__|Specify the user overrides for the initial Ignition configuration.|string
|*installConfigOverrides* +
__optional__|CDefine install configuration parameters.|string
|*machineNetwork* +
__optional__|CSpecify the list of the IP address pools for machines.|array
|*networkType* +
__optional__|Specify the Container Network Interface (CNI) plugin to install. The default value is `OpenShiftSDN` for IPv4, and `OVNKubernetes` for IPv6 or {sno} clusters.|string
|*proxy* +
__optional__|Define the proxy settings used for the install configuration of the cluster.|object
|*pullSecretRef* +
__required__|Configure the `pull-secret` file for pulling images.
When creating the `pull-secret` file, use the same namespace as the `ClusterInstance` CR that provisions the host.|object
|*serviceNetwork* +
__optional__|Specify the list of the IP address pools for services.|array
|*sshPublicKey* +
__optional__|Specify the public Secure Shell (SSH) key to provide access to instances.
This key is added to the host to allow SSH access.|string
|*suppressedManifests* +
__optional__|Specify a list of cluster-level manifests to exclude from the template rendering process.|array
|*nodes* +
__required__|Specify the configuration parameters for each node.|<<_rhacm-docs_apis_clusterinstance_jsoncluster_nodes,nodes>> array
|*templateRefs* +
__required__|CSpecify the list of the references to cluster-level templates.
A cluster-level template consists of a `ConfigMap` object, in which the keys of the data field represent the kind of the installation manifests.
Cluster-level templates are instantiated once per cluster in the `ClusterInstance` CR.|array
|===

[[_rhacm-docs_apis_clusterinstance_jsoncluster_nodes]]
*nodes*

[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|*automatedCleaningMode* +
__optional__|Set the value to `metadata` to enable the removal of the disk's partitioning table only, without fully wiping the disk.
The default value is `disabled`.|string
|*bmcAddress* +
__required__|BMC address that you use to access the host.
Applies to all cluster types.
For more information about BMC addressing, see _BMC addressing_ in Additional resources.
*Note:* In far edge Telco use cases, only virtual media is supported for use with {ztp}.|string
|*bmcCredentialsName* +
__required__|Configure the `bmh-secret` CR that you separately create with the host BMC credentials.
When creating the `bmh-secret` CR, use the same namespace as the `ClusterInstance` CR that provisions the host.|string
|*bootMACAddress* +
__required__|Specify the MAC address that PXE boots.
It is required for `libvirt` VMs driven by virtual BMC.|string
|*bootMode* +
__optional__|Set the boot mode for the host to `UEFI`.
The default value is `UEFI`.
Use `UEFISecureBoot` to enable secure boot on the host.
The following values are supported:

* `UEFI`
* `UEFISecureBoot`
* `legacy`|string
|*extraAnnotations* +
__optional__|Specify additional node-level annotations to be applied to the rendered templates.|object
|*extraLabels* +
__optional__|Specify additional node-level labels that applies to the rendered templates.|object
|*hostName* +
__required__|Define the host name.|string
|*installerArgs* +
__optional__|Specify the user overrides for the host's :op-system-first: installer arguments.|string
|*ignitionConfigOverride* +
__optional__|Specify the user overrides for the initial Ignition configuration.
Use this field to assign partitions for persistent storage.
Adjust disk ID and size to the specific hardware.|string
|*ironicInspect* +
__optional__|Specify if automatic introspection runs during registration of the bare metal host.
|string
|*nodeLabels* +
__optional__|Specify custom roles for your nodes in your managed clusters.
These are additional roles are not used by any {product-title} components, only by the user.
When you add a custom role, it can be associated with a custom machine config pool that references a specific configuration for that role.
Adding custom labels or roles during installation makes the deployment process more effective and prevents the need for additional reboots after the installation is complete.|object
|*nodeNetwork* +
__optional__|Configure the network settings for the node.|object
|*role* +
__optional__|Configure the role of the node, such as `master` or `worker`.
|string
|*rootDeviceHints* +
__optional__|Specify the device for deployment.
Identifiers that are stable across reboots are recommended.
For example, `wwn: <disk_wwn>` or `deviceName: /dev/disk/by-path/<device_path>`. `<by-path>` values are preferred.
For a detailed list of stable identifiers, see "About root device hints".
You can also specify the name, model, size, or vendor of the device.|object
|*suppressedManifests* +
__optional__|Specify a list of node-level manifests to exclude from the template rendering process.|array
|*templateRefs* +
__required__|Specify the list of the references to node-level templates.
A node-level template consists of a `ConfigMap` object, in which the keys of the data field represent the kind of the installation manifests.
Node-level templates are instantiated once for each node in the `ClusterInstance` CR.|array
|===

[[_rhacm-docs_apis_clusterinstance_jsoncluster_status]]
*status*

[options="header", cols=".^2a,.^3a,.^4a"]
|===
|Name|Description|Schema
|*conditions* +
__optional__|Lists the conditions that pertain to actions performed on the `ClusterInstance` resource.|<<_rhacm-docs_apis_clusterinstance_jsoncluster_conditions,conditions>> array
|*deploymentConditions* +
__optional__|Lists the hive status conditions that are associated with the `ClusterDeployment` resource.|<<_rhacm-docs_apis_clusterinstance_jsoncluster_deploymentconditions,deploymentConditions>> array
|*manifestsRendered* +
__optional__|Lists the manifests that have been rendered and their statuses.|array
|*observedGeneration* +
__optional__|Tracks the observed generation of manifests to avoid unnecessary reconciliation.|integer
|===

[[__rhacm-docs_apis_clusterinstance_jsoncluster_conditions]]
*conditions*

[options="header", cols=".^2a,.^3a"]
|===
|Type|Description
|*ClusterInstanceValidated* +
|Indicates that the {sco} validated the `ClusterInstance` `spec` fields and verified that the required artifacts, such as secrets and extra manifest `ConfigMaps` objects are present.

|*RenderedTemplates* +
|Indicates that {sco} successfully validated the referenced Golang cluster templates.

|*RenderedTemplatesValidated* +
|Indicates that the {sco} rendered the installation manifests and the dry run was successful.

|*RenderedTemplatesApplied* +
|Indicates that the {sco} created the installation manifests and the underlying Operators consumed them.

|*Provisioned* +
|Indicates that the underlying Operators are provisioning the clusters.
|===

[[_docs_apis_clusterinstance_jsoncluster_deploymentconditions_]]
*deploymentConditions*

[options="header", cols=".^2a,.^3a"]
|===
|Type|Description
|*ClusterInstallRequirementsMet* +
|Indicates that the installation can start.

|*ClusterInstallCompleted* +
|Indicates that the cluster installation was successful.

|*ClusterInstallFailed* +
|Indicates that the cluster installation failed.

|*ClusterInstallStopped* +
|Indicates that the cluster installation stopped.
|===

[[_rhacm-docs_apis_clusterinstance_additional_resources]]
*Additional resources*

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/installing/deploying-installer-provisioned-clusters-on-bare-metal#bmc-addressing_ipi-install-installation-workflow[BMC addressing]